// The adjectives are taken and cherry-picked from https://www.paperrater.com/page/lists-of-adjectives.
export const ADJECTIVES = [
  'agreeable',
  'ambitious',
  'brave',
  'calm',
  'delightful',
  'eager',
  'faithful',
  'gentle',
  'happy',
  'kind',
  'lively',
  'nice',
  'polite',
  'proud',
  'silly',
  'thankful',
  'victorious',
  'witty',
  'wonderful',
  'zealous'
];

// The nouns are taken and cherry-picked from https://eslgrammar.org/list-of-nouns/.
export const NOUNS = [
  'answer',
  'balloon',
  'caravan',
  'diamond',
  'dream',
  'energy',
  'flower',
  'forest',
  'garden',
  'glass',
  'helmet',
  'honey',
  'ice',
  'juice',
  'kite',
  'library',
  'morning',
  'notebook',
  'ocean',
  'piano',
  'quill',
  'rain',
  'refrigerator',
  'school',
  'telephone',
  'umbrella',
  'vase',
  'window',
  'yak',
  'zebra'
];
